# Generated by Django 6.1.1 on 2026-09-25 10:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('phone_number', models.CharField(help_text='Stored in international format, e.g. +234...', max_length=20, unique=True)),
                ('email', models.EmailField(blank=True, max_length=150, null=True)),
                ('photo', models.FileField(blank=True, null=True, upload_to='members/photos/')),
                ('date_joined', models.DateField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'member',
                'ordering': ['-date_joined', 'full_name'],
            },
        ),
    ]
