# Generated by Django 6.1.1 on 2026-10-02 14:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='last_inactivity_reminder_at',
            field=models.DateTimeField(blank=True, help_text='Tracks when the 14-day inactivity reminder was last sent to avoid duplicate messages.', null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='date_joined',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
