# Generated by Django 6.1.1 on 2026-09-25 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='check_ins', to='members.member')),
            ],
            options={
                'db_table': 'check_in',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['member', 'timestamp'], name='checkin_member_time_idx')],
            },
        ),
    ]
