# Generated by Django 6.1.1 on 2026-10-02 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_member_last_inactivity_reminder_at_and_more'),
        ('memberships', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReminderTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='Template identifier: expiry_3d, lapsed_7d, lapsed_30d, lapsed_60d, inactive_14d, welcome_sub', max_length=50, unique=True)),
                ('title', models.CharField(max_length=150)),
                ('body', models.TextField(help_text='Template text. Supports variables like {name}, {plan_name}, {end_date}, {days_left}, {price}')),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'reminder_template',
                'ordering': ['key'],
            },
        ),
        migrations.AddField(
            model_name='subscription',
            name='lapsed_stage',
            field=models.PositiveSmallIntegerField(default=0, help_text='Lapsed milestone tracking: 0=none, 1=7d sent, 2=30d sent, 3=60d sent'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='last_lapsed_reminder_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['status', 'end_date', 'lapsed_stage'], name='sub_status_lapsed_idx'),
        ),
    ]
